### ISSUE TITLE
Multiple Layers using short cut strings

### ISSUE THREAD

**Issue by gursel58** [Sibilino/yii2-openlayers#3]
I created a map with one tile layer and multiple vector layers. If I use the full vector layer specification all of the layers display properly, if I use the short cut layer specification only the tile and last vector layer is displayed.

in this example only the time layer and the last vector layer are displayed:
echo OpenLayers::widget([
    'id' => 'lightning',
    'options' => [],  
    'mapOptions' => [
        'layers' => [
            'Tile' => [ // Generates "new ol.layer.Tile()" JS. See below for an explanation of the OL class.
                'source' => new OL('source.MapQuest', [
                    'layer' => 'sat',
                    ]),
                ],
            'Vector' => [
                'source'=> new OL( 'source.Vector',[
                           'url' =>'/strikes2day_uncoor.json',
                           'format' => new OL('format.GeoJSON', [
                                'projection' => 'EPSG:3857',
                                 ]),
                            ]),
                        ],  

```
        'Vector' => [
            'source' => new OL('source.Vector', [
                        'url' => '/strikes30day_test.kml',
                        'format' => new OL('format.KML', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ])
                    ],
        'Vector' => [
            'source' => new OL('source.Vector', [
                        'url' => '/MasterCircle.kml',
                        'format' => new OL('format.KML', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ])
                    ],
        'Vector' => [
            'source' => new OL('source.Vector', [
                        'url' => '/detectors.kml',
                        'format' => new OL('format.KML', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ])
                    ],      

        ],
```

In this example all layers are displayed:

echo OpenLayers::widget([
    'id' => 'lightning',
    'options' => [],  
    'mapOptions' => [
        'layers' => [
            new OL('layer.Tile', [ // Generates "new ol.layer.Tile()" JS. See below for an explanation of the OL class.
                'source' => new OL('source.MapQuest', [
                    'layer' => 'sat',
                ]),
            ]),

```
          new OL('layer.Vector', [
          'source'=> new OL( 'source.Vector',[
                       'url' =>'/strikes2day_uncoor.json',
                       'format' => new OL('format.GeoJSON', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ]),
                    ]), 

              new OL('layer.Vector', [
                'source'=> new OL( 'source.Vector',[
                       'url' => '/strikes30day_test.kml',
                       'format' => new OL('format.KML', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ]),
                    ]),             

              new OL('layer.Vector', [
                'source'=> new OL( 'source.Vector',[
                       'url' => '/MasterCircle.kml',
                       'format' => new OL('format.KML', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ]),
                    ]), 

              new OL('layer.Vector', [
                'source'=> new OL( 'source.Vector',[
                       'url' => '/detectors.kml',
                       'format' => new OL('format.KML', [
                            'projection' => 'EPSG:3857',
                             ]),
                        ]),
                    ]), 

        ],
```

Am I misunderstanding the use of the short cut format ?
Otherwise the extension works great.

Thanks
Greg

**Comment by e-dric** [comment]
Hello,

Looks like this is a bug.

My bet is [this line](https://github.com/Sibilino/yii2-openlayers/blob/master/widget/OpenLayers.php#L101) overwriting previous positions in the processed array.

I will confirm and patch this issue in the next few days.

Thanks for the find!

**Comment by Sibilino** [comment]
Hello,

Looks like this is a bug.

My bet is [this line](https://github.com/Sibilino/yii2-openlayers/blob/master/widget/OpenLayers.php#L101)
overwriting previous elements in the processed array.

I will confirm and correct this issue as soon as I can within the next few
days.

Thanks for the find!

2015-10-25 3:42 GMT+01:00 gursel58 notifications@github.com:

**Comment by Sibilino** [comment]
Wait, I did not read your example carefully enough. You are using the same string index multiple times! 

It is not a bug, it is just that it is impossible to define multiple array elements with the same key. So, your array declaration contains 1 element with the key "Vector", but it is redefined multiple times... This is kind of a limitation of the short syntax, I am afraid that you will need to use the full OL() notation for your use case.

Thanks for pointing out this subtlety, it help find some weak code and improve documentation.

Regards
